### ISSUE TITLE
Paste and afterPaste unit tests fails on IE 11

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor4-angular#104]
## Are you reporting a feature request or a bug?

Failing tests

## Provide detailed reproduction steps (if any)

Follow up of #7 (#21).

There is an issue with mocked paste event on IE 11 (probably related to some `dataTransfer` differences and different clipboard flow on IE 11).

See https://travis-ci.org/github/ckeditor/ckeditor4-angular/builds/683430234#L437.

## Other details

* Browser: IE 11
* OS: Windows
* Integration version: Latest `master`
* CKEditor version: 4.14
* Installed CKEditor plugins: -

**Comment by bhugot** [comment]
Same on Firefox
