### ISSUE TITLE
Critical bug when ckeditor removed from dom before loaded

### ISSUE THREAD

**Issue by bhugot** [ckeditor/ckeditor4-angular#110]
## Are you reporting a feature request or a bug?

Hello, we found a bug maybe related to ckeditor itself. if the component is removed from dom before initialisation you get Cannot read property 'unselectable' of null.

here is a sample https://stackblitz.com/edit/angular-ivy-rgaeks?file=src%2Fapp%2Fdemo%2Fdemo.component.ts

If you either have a way to fix this or could fix it.
Regards

**Comment by bhugot** [comment]
The fix is here #111

**Comment by f1ames** [comment]
Fixed in d3ceee6.

**Comment by bhugot** [comment]
Any ETA on release? Thanks

**Comment by f1ames** [comment]
We plan to release new version next week.

**Comment by f1ames** [comment]
Hi @bhugot, the new package version (`1.2.2`) with the fix is out on NPM (https://www.npmjs.com/package/ckeditor4-angular) :tada::clap:

**Comment by boris27** [comment]
hi guys, i have little different situation, and your fix in `1.2.2` doesnt work for me

this is example of above code, little modified to exampled my situation)
https://stackblitz.com/edit/angular-ivy-taveju?file=src%2Fapp%2Fapp.component.ts

can you help with this? @f1ames

**Comment by f1ames** [comment]
Hi @boris27,

please report a separate issue in this repository describing your case so we can keep track of your issue.
