### ISSUE TITLE
Add release tools

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor4-angular#13]

**Comment by f1ames** [comment]
From what I see there is now `ng build` (and `ng-build --prod`) and also `build-package` script (which uses `ng-packagr` underneath).

I assume `build-package` was used previously to build package published to npm? So few thinks:

* Do we need `ng build` command itself or could we always use `ng-packagr`? Now it is a little confusing that we have two ways to build the package.
* What advantage `ng-packagr` gives as over using regular `ng build`?
* When it comes to `npm publish` we could use `prepublishOnly` package script same as in [our React integration](https://github.com/ckeditor/ckeditor4-react/blob/e79d1faa6ac23a33348489bdfcbafdf28f3c8661/package.json#L17).

cc @engineering-this @jacekbogdanski

**Comment by engineering-this** [comment]
`ng build` is a command implemented by `angular-cli`. It builds the project with examples which are used for manual testing. Additionally calling `ng test` or `ng e2e` will in fact do `ng build` before running automated tests. 

`build-package` uses only files from `src/ckeditor` to build the CKEditor component which is the only way to build package for publishing on NPM.

**Comment by engineering-this** [comment]
☝️ Actually README should be updated with above information.

**Comment by f1ames** [comment]
Ok, makes sense👌

So my proposal for solving this issue is to update the readme file as proposed in the above comment and `package.json` by adding `prepublishOnly` step which runs `build-package` script.

One more thing to check is `ng build --prod`. I am able to successfully run `ng build` and `npm run build-package`, but `ng build --prod` throws some errors:

![image](https://user-images.githubusercontent.com/1061942/55873447-02172400-5b90-11e9-8157-98feef9bb5e3.png)

**Comment by engineering-this** [comment]
Actually there is another issue. Both `build-package` and `ng build` outputs to same `dist` directory.

**Comment by engineering-this** [comment]
>One more thing to check is ng build --prod. I am able to successfully run ng build and npm run build-package, but ng build --prod throws some errors:

It's some issue with `webpack` and `terser-js`, probably playing around with different versions of these would fix that issue, however it might bring new problems. I'd remove information about `--prod` flag from README, we don't need to build `production` version of samples as they are only for internal use.
