### ISSUE TITLE
How to show the Upload button in Image picker?

### ISSUE THREAD

**Issue by nehal076** [ckeditor/ckeditor4-angular#134]
I'm using the `"ckeditor4-angular": "^1.3.0"` version

But in my image picker, there are only 2 tabs

![screenshot-localhost_4200-2020 09 09-16_02_01](https://user-images.githubusercontent.com/32421196/92587879-dd0f6f00-f2b5-11ea-9ddf-fee72ec6578e.png)

However, in the [docs](https://ckeditor.com/docs/ckeditor4/latest/examples/angular.html#/editor-types), we can clearly see there is an '**Upload**' option. 

![screenshot-ckeditor com-2020 09 09-16_06_01](https://user-images.githubusercontent.com/32421196/92588430-94a48100-f2b6-11ea-9129-9f38269485cd.png)

This is my template

`    <ckeditor formControlName="promoContent">/ckeditor>`

And this my module
```
import { CKEditorModule } from 'ckeditor4-angular';
@NgModule({
  declarations: [TemplateManagementComponent, ManagePromotionsComponent],
  imports: [
     ...
    CKEditorModule
  ]
```
How can I configure this?

**Comment by Dumluregn** [comment]
Hello, to have this options you need to use [CKFinder](https://ckeditor.com/docs/ckfinder/ckfinder3/#!/guide/dev_ckeditor), which is a separate product offered by CKSource. If you are interested in using it, please [contact us](https://ckeditor.com/contact/).

**Comment by f1ames** [comment]
@nehal076 @Dumluregn please keep in mind that it's also possible to use custom integration - see https://ckeditor.com/docs/ckeditor4/latest/guide/dev_howtos_file_upload.html#how-do-i-upload-files-or-images-using-ckeditor-4.

**Comment by nehal076** [comment]
@f1ames Will you please provide a Stackblitz using custom integration of this Upload button in Angular?
