### ISSUE TITLE
[Question] Please help me answer the question

### ISSUE THREAD

**Issue by donhuvy** [ckeditor/ckeditor4-angular#145]
https://stackoverflow.com/questions/64493739/angularjs-how-to-init-variable-if-only-when-it-did-not-exist

**Comment by jacekbogdanski** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them. If you have CKEditor license, please contact our support team.

**Comment by Dumluregn** [comment]
By the way, the package you use (`angular-ckeditor`) is not an official integration provided through this repository `ckeditor4-angular` package.
