### ISSUE TITLE
autocomplete plugin is not working in ckeditor4-angular

### ISSUE THREAD

**Issue by sedhurabe** [ckeditor/ckeditor4-angular#154]
In my project, I need to implement the CKeditor4 autocomplete with reference to [https://ckeditor.com/docs/ckeditor4/latest/examples/autocomplete.html.](url) I had followed the same approach in my angular project but it not working for me. My worked example is [https://stackblitz.com/edit/ckeditor-autocomplete?file=src/app/app.component.ts](url)

**Comment by Dumluregn** [comment]
Hello, I see you also opened #156 (I transferred it from `ckeditor4` since it concerns `ckeditor4-angular` repo) containing more details, so I'm closing this issue.
