### ISSUE TITLE
[IE11] Module loads with es6 functions

### ISSUE THREAD

**Issue by rpinco** [ckeditor/ckeditor4-angular#169]
Hey guys, im trying to load the module with IE11 and its throwing a syntax error, due to the module being loaded with arrow functions (which are not compatible with es5/IE11)

## Are you reporting a feature request or a bug?
Bug

## Provide detailed reproduction steps (if any)

1. … Load module within Angular
2. … Load page in IE11

### Expected result

That the module loads correctly

### Actual result

SyntaxError1002 due to arrow functions present on build

## Other details

* Browser: IE11
* OS: Windows
* Integration version: v2.1.0
* CKEditor version: 4
* Installed CKEditor plugins: none

**Comment by sculpt0r** [comment]
Hi @rpinco ,

Thank you for your report. I can confirm this issue.

**Comment by Dumluregn** [comment]
This issue was resolved with https://github.com/ckeditor/ckeditor4-integrations-common/commit/fdb7e73962d20264728208da22d1b608dab271bd.
