### ISSUE TITLE
Plugins support.

### ISSUE THREAD

**Issue by knz237** [ckeditor/ckeditor4-angular#185]
## Provide detailed reproduction steps (if any)

WE took the latest of CKEditor4-anglar
WE want to add our custom plugin to the Editor
Chedked in the node modules folder of the library
couldnot  find where to add the plugins / plugin folder as suggested in official ckeditor site.

### Expected result

A Plugin folder sould be abailable to add custom plugins

### Actual result

Not able to add any plugins

## Other details

Thanks

**Comment by Dumluregn** [comment]
Hello, you need to use [`CKEDITOR.plugins.addExternal()` method](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_plugins.html#method-addExternal) and include the plugin in the[ custom config](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_angular.html#customizing-ckeditor-preset-or-version).

Please note that our GitHub issue tracker serves for reporting bugs and new features only, so I'm closing this issue.

**Comment by ronaldohoch** [comment]
Have this issue too.
I have a custom build with custom made plugins.

Here my files:
```html
<ckeditor 
    data="<p>Hello, world!</p>"
    [config]="config"
    (ready)="onReady($event)"
    ></ckeditor>
```

Tried on the ngOnInit using the CKEDITOR variable.
Tried on the (ready)="" function using event.editor.plugins.addExternal("dinux_links","http://localhost:8080/plugins/dinux_links/plugin.js")
Tried on the (ready) using the CKEDITOR variable.

```typescript
import { Component, OnInit } from '@angular/core';

import { CKEditor4 } from 'ckeditor4-angular/ckeditor';

declare var CKEDITOR:any;

@Component({
  selector: 'dinamize-nx-workspace-ckeditor',
  templateUrl: './ckeditor.component.html',
  styleUrls: ['./ckeditor.component.css']
})
export class CkeditorComponent implements OnInit {
  config={
    language: "pt-br",
    extraPlugins: 'dinux_links',
    toolbar: [
        {name: 'basicstyles', groups: ['basicstyles', 'cleanup'], items: ['Bold', 'Italic', 'Underline', '-', 'RemoveFormat']},
        {name: 'paragraph', groups: ['align'], items: ['JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock']},
        {name: 'styles', items: ['Format', 'Font', 'FontSize']},
        {name: 'Adds', groups: ['addons_dinux'], items: ['dinux_links', 'Source']},
    ]
  }
  constructor() {
    
  }

  ngOnInit(): void {
    CKEDITOR.plugins.addExternal("dinux_links","http://localhost:8080/plugins/dinux_links/plugin.js");
  }

  onReady(event: CKEditor4.EventInfo){
    // console.log("editor",event.editor);
    CKEDITOR.plugins.addExternal("dinux_links","http://localhost:8080/plugins/dinux_links/plugin.js");
    // event.editor.plugins.addExternal("dinux_links","http://localhost:8080/plugins/dinux_links/plugin.js")
  }
}
```

Don't work :/
