### ISSUE TITLE
Error using ckeditor with material tabs

### ISSUE THREAD

**Issue by ronaldohoch** [ckeditor/ckeditor4-angular#192]
## Are you reporting a feature request or a bug?
Bug

## Provide detailed reproduction steps (if any)

1. Create a new project
2. Install Angular Material and CkEditor
3. Configure the Material Tab
4. Add 2 tabs with ckeditor inside of it
5. Link to see: https://stackblitz.com/edit/angular-wod9yb?file=src/app/tab-group-basic-example.html
6. You can comment the line 6 and application will work
7. If you go to second tab and go back to the first, the ckeditor will be broken

### Expected result

Ckeditor working normaly

### Actual result

Ckeditor broken

## Other details

* Browser: Chrome Last Version
* OS: Windows 10 Last Build
* Integration version: 2.2.0
* CKEditor version: A custom build of 4.4.2, revision: 1567b48
* Installed CKEditor plugins: many custom.
* (In the stackblitz example, it use the raw package and throws the same error)

**Comment by Dumluregn** [comment]
Hello, this is the same issue as just reopened https://github.com/ckeditor/ckeditor4-angular/issues/114, so I'm closing it as a duplicate - however thank you for the sample, it will probably be helpful when we'll be testing if the fix in `ckeditor4` works fine.
