### ISSUE TITLE
CKEditor not opening in fixed UI mode after setting type as inline and added extraPlugins divarea

### ISSUE THREAD

**Issue by agabhane** [ckeditor/ckeditor4-angular#198]
## Are you reporting a feature request or a bug?
Bug

## Provide detailed reproduction steps (if any)

1. As explained [here](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_angular.html#using-the-div-based-editor-type), configure the ckeditor with extraPlugins `divarea` and set `type` as `inline`

### Expected result

*The editor should get opened with div tag and toolbar should be fixed like [Fixed UI](https://ckeditor.com/docs/ckeditor4/latest/features/uitypes.html#fixed-ui-for-inline-editor)*

### Actual result

*The editor is getting opened in div tag with floating toolbar like [Floating UI](https://ckeditor.com/docs/ckeditor4/latest/features/uitypes.html#floating-user-interface)*

![image](https://user-images.githubusercontent.com/8133509/120449388-02e12480-c3ad-11eb-99c8-f7d5ace5d03d.png)

## Other details

* Browser: Chrome Version 90.0.4430.212 (Official Build) (64-bit)
* OS: Windows 10 
* Integration version: 
* ckeditor4-angular: 2.2.0 
* ckeditor4-integrations-common: 0.2.0
* CKEditor version: 4.16.0
* Installed CKEditor plugins: format,imagepaste,font,maximize,image,sourcedialog,uploadimage,table,find,link,pastefromword,pagebreak,scayt,image,filebrowser,justify,colorbutton,colordialog,tabletools,tableresize,tableselection,dialogadvtab,liststyle,indentblock,indent,divarea

**Comment by Dumluregn** [comment]
Hello, docs seems to be incorrect. To have a `divarea` editor you only have to add a `divarea` plugin and don't need to change editor type - see [the sample from this repo](https://github.com/ckeditor/ckeditor4-angular/blob/master/src/app/demo-form/demo-form.component.html#L17-L22). Sorry for the confusion in documentation, we'll fix it ASAP.

**Comment by Dumluregn** [comment]
Closed in https://github.com/ckeditor/ckeditor4-docs/pull/362.
