### ISSUE TITLE
Upgrade ckeditor4-integrations-common

### ISSUE THREAD

**Issue by MMMalik** [ckeditor/ckeditor4-angular#201]
## Are you reporting a feature request or a bug?

Task

## Provide detailed reproduction steps (if any)

There is a new major version of `ckeditor4-integrations-common` package available as per [this PR](https://github.com/ckeditor/ckeditor4-integrations-common/pull/18). It should be used downstream in the integrations to reduce library sizes.

⚠️ Warning ⚠️ 

This is potentially a breaking change. Version `1.0.0` of `ckeditor4-integrations-common` does not contain `Promise` polyfill anymore. Some downstream packages might (unknowingly) rely on that polyfill though. New major version of `ckeditor4-angular` might be required for this change.

**Comment by Dumluregn** [comment]
Done in https://github.com/ckeditor/ckeditor4-angular/pull/207. Note about releasing the next major was moved to #209.
