### ISSUE TITLE
Add sample with Angular router

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor4-angular#217]
It looks like we don't have any sample allowing us to test how the editor would behave with the browser router. As an example, we already have an issue with maximize plugin (https://github.com/ckeditor/ckeditor4/issues/4374) that requires Angular router to reproduce. Also see https://github.com/ckeditor/ckeditor4-angular/issues/141

**Comment by Comandeer** [comment]
Actually the whole example is based on Angular router with two routes. Probably we could treat the whole sample app as a router example, WDYT?

**Comment by jacekbogdanski** [comment]
Let's check if we are able to reproduce https://github.com/ckeditor/ckeditor4-angular/issues/141 as I didn't manage to do it with the actual sample.

**Comment by Comandeer** [comment]
It's reproducible with the current sample.

Without fix:

https://user-images.githubusercontent.com/1078728/132699021-f0cf5501-b0aa-42d6-9bb5-c5e175d801d4.mov

With fix:

https://user-images.githubusercontent.com/1078728/132699098-eced35bb-9ac9-4f16-b025-d099a88f246e.mov
