### ISSUE TITLE
Provide custom plugins inplementation

### ISSUE THREAD

**Issue by synopss** [ckeditor/ckeditor4-angular#228]
## Are you reporting a feature request or a bug?

Feature request

## Other details

The idea is to be able to create custom plugins as it is possible with the non angular ckeditor library : https://ckeditor.com/docs/ckeditor4/latest/guide/plugin_sdk_sample.html

**Comment by Comandeer** [comment]
Could you provide a sample use case for such a plugin system?

**Comment by synopss** [comment]
@Comandeer 
Sure, for example, being able to create a custom button that will trigger something outside of the textfield (let's say a modal where you can select something to put in the editor)

**Comment by synopss** [comment]
Ok, let's try to explain you one use case.

I am using this editor; I can add a lot of buttons giving styles to the content that I am writing into the editor. Those buttons are native.

I would like to add a custom button that will add a specific text into the texterea. It only has to be triggered after clicking on this specific button.

Right now, I have to use a custom button outside the editor because I can't add it into the editor. That's whole point of my proposal, being able to create custom buttons with custom triggering.

**Comment by Comandeer** [comment]
You can add buttons to the editor without creating a new plugin: https://codesandbox.io/s/hidden-tdd-xmii16?file=/src/app/app.component.ts

Additionally, if the additional plugins are needed, you can provide a [link to the custom CKEditor 4 build](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_angular.html#customizing-ckeditor-preset-or-version) that would contain such a plugin.

We do not plan to duplicate plugin functionality in packages integrating CKEditor 4 with various frameworks.
