### ISSUE TITLE
Open empty page when I click on image with hyperlink url created with ckeditor4-angular editor

### ISSUE THREAD

**Issue by vinod459** [ckeditor/ckeditor4-angular#234]
Hi,

I have created img tag with hyperlink using ckeditor4-angular and stored in my application. And in the view page when I click on the image it is opening a new blank page. But hyperlink without the image it is working. Here is the code created when I create image with hyperlink for your reference. Appreciate your help on this issue. Thanks in advance!

Image with hyperlink which is not working in Ckeditor4 sample(view html source for below):
<p style="text-align:center"><a href="https://www.google.com/search?q=cloud&rlz=1C1GCEA_enSG805SG806&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjFs--foe75AhXdFbcAHabtAgQQ_AUoAXoECAMQAw&biw=1280&bih=913&dpr=1#imgrc=XiQIPAZblWHEIM"><img src="https://images.unsplash.com/photo-1504253163759-c23fccaebb55?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxleHBsb3JlLWZlZWR8MXx8fGVufDB8fHx8&w=1000&q=80" /></a></p>

Text with hyperlink working in Ckeditor4 sample(view html source for below):
<p style="text-align:center"><a href="https://www.google.com/search?q=cloud&rlz=1C1GCEA_enSG805SG806&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjFs--foe75AhXdFbcAHabtAgQQ_AUoAXoECAMQAw&biw=1280&bih=913&dpr=1#imgrc=e72vg_rb6DDH1M">Original file</a></p>

ckeditor4-angular
* CKEditor version: ckeditor4-angular@1.2.2
* 

Thank You

**Comment by KarolDawidziuk** [comment]
Hi @vinod459 

Could you provide a working example that will showing your issue?

You can use one of our samples to create the reproduction sample:

* CodePen: https://codesandbox.io/s/f5y9f?file=/src/app/app.component.html
* StackBlitz: https://stackblitz.com/edit/ckeditor4-angular-bug-report?file=src%2Fapp%2Fapp.component.html
