### ISSUE TITLE
ckeditor4-angular package on npm is still not compatible with angular v16

### ISSUE THREAD

**Issue by Muntazir86** [ckeditor/ckeditor4-angular#244]
ckeditor4-angular package on npm is still not compatible with angular v16.
@Comandeer kindly update package on npm so that we can use package seamlessly.
Thank you in advance

**Comment by jacekbogdanski** [comment]
@Muntazir86 the angular integration is going to be released alongside CKEditor 4. The release is planned for June/July.

**Comment by henkkelder** [comment]
It appears the just released version 4.0.0 does not support Angular 16 :-(

`This likely means that the library (ckeditor4-angular) which declares CKEditorModule is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
`
