### ISSUE TITLE
Please publish last version to NPM to support Angular 16.

### ISSUE THREAD

**Issue by henkkelder** [ckeditor/ckeditor4-angular#248]
On NPM version 3.3.0 is the last version published in March.

Could you publish the last version on NPM?

For now, as a tempory workaround, I have cloned this respos to @henkkelder/ckeditor4-angular and published that version on NPM.
But it is better to publish here.

**Comment by Comandeer** [comment]
Please see https://github.com/ckeditor/ckeditor4-angular/issues/244#issuecomment-1580926181 for more details.
