### ISSUE TITLE
The editor window is not loading after updating from version 4.0.1 to 5.1.0.

### ISSUE THREAD

**Issue by sharath-mv** [ckeditor/ckeditor4-angular#256]
The editor window is not loading in my angular(12.0.2) application  after updating from version 4.0.1 to 5.1.0.

**Comment by jacekbogdanski** [comment]
CKEditor 4 angular integration 5.0 and above use secure, LTS version of the editor that is available under commercial terms of the ["Extended Support Model"](https://ckeditor.com/ckeditor-4-support/). CKEditor 4 reached its end of life on June 30, 2023, and the open version can no longer be considered secure.

There are 3 choices currently:
* use non-secure, open version of the editor by downgrading the integration to 4.0.1, or replacing the default editor CDN to open source version (4.22.1 and below)
* acquire the Extended Support Model to use CKEditor 4 with security updates and critical bug fixes guaranteed until December 2026.
* switch to CKEditor 5

Please, [contact our support team](https://ckeditor.com/contact-sales/#contact-form) if you would like to learn more about secure options.
