### ISSUE TITLE
CKEditor 4.14.0 version is not secure

### ISSUE THREAD

**Issue by PedroTheRealOne** [ckeditor/ckeditor4-angular#259]
I'm using the lastest version: `"ckeditor4-angular": "^5.1.0",`.
But today 07/01/24 I got the message on the component: "This CKEditor 4.14.0 version is not secure. Consider [upgrading to the latest one](https://ckeditor.com/ckeditor-4-support/), 4.24.0-lts.".

![image](https://github.com/ckeditor/ckeditor4-angular/assets/17551274/7d3fbb4b-691b-4f2e-b484-0b5765723966)

Any plans on updating the angular version to the safest?

Ps.: There is a fix for the message: 
`versionCheck: false`

**Comment by jacekbogdanski** [comment]
@PedroTheRealOne the latest angular component uses 4.24.0-lts by default, so my guess is that you configured CDN link by yourself using the option [editorURL](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_angular.html#customizing-ckeditor-preset-or-version).

Please, note that 4.24.0-lts is the only secure CKEditor 4 version, all open source versions are considered non-secure. **If you change the `versionCheck` to false that doesn’t mean you are using a secure CKEditor 4.**

You can learn more about why that notification was introduced in our blog post: https://ckeditor.com/blog/important-update-for-ckeditor-4-users/

If you are interested in more details about CKEditor 4 LTS (secure version of the editor), [please contact us directly](https://ckeditor.com/contact-sales/#schedule-meeting).

**Comment by MostafaHamdy3** [comment]
@PedroTheRealOne 
Did you find a solution to this issue?

**Comment by PedroTheRealOne** [comment]
> @PedroTheRealOne Did you find a solution to this issue?

Yes, like @jacekbogdanski told, I was using the unsafed version using the option [editorURL](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_angular.html#customizing-ckeditor-preset-or-version)

But seems like the `4.24.0-lts` it's under some commercial terms
![image](https://github.com/ckeditor/ckeditor4-angular/assets/17551274/91e457f4-d886-41ae-b2fc-188837c91a11)
