### ISSUE TITLE
Set global config value

### ISSUE THREAD

**Issue by angelika** [ckeditor/ckeditor4-angular#29]
I would like to be able to use both the ckeditor and have divs with contenteditable, without the editor. I've found the disableAutoInline config value, but how do I change a global config value using this module? Is it possible?

**Comment by f1ames** [comment]
Hello @angelika,
the component uses [`CKEDITOR.inline()`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR.html#method-inline) underneath which turns only given element into CKEditor instance (in opposite to [`CKEDITOR.inlineAll()`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR.html#method-inlineAll)) so it shouldn't be a problem to have a plain `div[contenteditable=true]` and `disableAutoInline` config should not be necessary.

You may refer to [Angular integration docs](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_angular.html#choosing-the-editor-type) for more details on integration.

**Comment by angelika** [comment]
Hi! 
I created the issue because the editor hooks in wherever I have a contenteditable div. So, it is a problem. I have "solved" it by downloading my own build and linking to that in the index.html file of my application.

**Comment by f1ames** [comment]
Would it be possible for you to prepare a minimalistic demo (e.g. on codepen) which reproduces this issue so we can take a look on this case?

**Comment by angelika** [comment]
I will try and find the time after my next deadline. In the meantime, I can tell you that I am using angular 7.2.15 and ckeditor4-angular 0.1.1 and I don't show the editor until the user clicks an edit button, if that gives you any clues.

**Comment by Dumluregn** [comment]
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.
