### ISSUE TITLE
Most settings are missing

### ISSUE THREAD

**Issue by Neill83** [ckeditor/ckeditor4-angular#33]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. … install it in angular 7 app
2. … add own config to editor from [here](https://ckeditor.com/latest/samples/toolbarconfigurator/index.html#advanced)
3. … just copy the code and paste it into your .ts file
4. ... run "npm start" and see that the most settings are missing

### Expected result
all settings are visible

### Actual result
just a few are visible
![image](https://user-images.githubusercontent.com/9987324/58950040-25281380-878e-11e9-81eb-961c6136e25a.png)

## Other details

* Browser: … Chrome
* OS: … MacOs Mojave
* Integration version: … 
* CKEditor version: …1.0.0-beta
* Installed CKEditor plugins: …

**Comment by f1ames** [comment]
Angular integration fetches `standard-all` preset by default. It means all plugins are available, however by default only these for `standard` preset are enabled (see https://ckeditor.com/ckeditor-4/download/ or https://github.com/ckeditor/ckeditor-presets/blob/master/presets/standard-build-config.js) so apart from changing toolbar configuration, you need to enable desired plugins (via [`config.plugins`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-plugins) or [`config.extraPlugins`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-extraPlugins)).

**Comment by Neill83** [comment]
Thanks for your response. I got it working with

`<ckeditor [editorUrl]="'https://cdn.ckeditor.com/4.11.4/full-all/ckeditor.js'" [config]="config"></ckeditor>`

and defining each field I needed in the "config"

Thanks
