### ISSUE TITLE
[BUG] ElementRef is not generic

### ISSUE THREAD

**Issue by abjbos** [ckeditor/ckeditor4-angular#37]
## Reproduction steps

1. `$ npm install`
2. `$ ng serve`

### Expected result

*The application compiles.*

### Actual result

An error is thrown during compilation:
```
ERROR in node_modules/ckeditor4-angular/ckeditor.component.d.ts(113,29): error TS2315: Type 'ElementRef' is not generic.
```

### Can be 'fixed' with

node_modules/ckeditor4-angular/ckeditor.component.d.ts(113,29):
```
-- constructor(elementRef: ElementRef<HTMLElement>, ngZone: NgZone);
++ constructor(elementRef, ngZone: NgZone);
```

## Other details

* Browser: any
* OS: MacOS / Linux (and probably Windows)
* CKEditor version: 1.0.0-beta
* Installed CKEditor plugins: none
* Angular version: 5.2.11

**Comment by f1ames** [comment]
This will be fixed with #40.

**Comment by bossan** [comment]
Thank you!

**Comment by abjbos** [comment]
Thank you!
