### ISSUE TITLE
CKFinder

### ISSUE THREAD

**Issue by M-Blobby** [ckeditor/ckeditor4-angular#47]
Hello,
There is a way to use CKFinder with ckeditor4-angular ?

**Comment by f1ames** [comment]
Hello @M-Blobby,
to use CKFinder with CKEditor 4 Angular integration you just need to set up CKFinder (the [usual procedure](https://ckeditor.com/docs/ckfinder/ckfinder3/#!/guide/dev_installation)) and then [add few configuration options while initializing CKEditor 4](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_ckfinder_integration.html#manual-integration-with-configuration-settings).

The only difference between using CKFinder with CKEditor 4 and CKEditor 4 Angular integration is the way how the config object is declared/passed - please see [our Angular docs for reference](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_angular.html#config).

**Comment by M-Blobby** [comment]
Hello @f1ames ,
Thank you for your answer :)
Do you have an example for the config object declared in the component ? There is something to add in "extraPlugins" ?
