### ISSUE TITLE
Enable IE polyfills

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor4-angular#5]
Using integration on IE9-11 requires enabling polyfills at `src/polyfills.ts`. We need to do some research to make sure that it's working correctly and if possible do it conditionally depending on the used browser. Angular may already cover this case - confirmation needed.

**Comment by f1ames** [comment]
I agree with @engineering-this, that polyfills should be on user/developer side. So if the app should support older IEs, then one can include polyfills. It's not the integration to make such decisions.
