### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor4-angular#52]
## Are you reporting a feature request or a bug?

Task

## Provide detailed reproduction steps (if any)

See:
* https://david-dm.org/ckeditor/ckeditor4-angular
* https://david-dm.org/ckeditor/ckeditor4-angular?type=dev

We probably should update all angular core packages to latest `stable` versions.

Related issue - #32.

**Comment by Dumluregn** [comment]
![image](https://user-images.githubusercontent.com/10883184/67770401-9d9db280-fa56-11e9-9e7b-e37cb6b3572d.png)
