### ISSUE TITLE
Two-way binding does not work when 'undo' plugin is removed

### ISSUE THREAD

**Issue by kandonorbert** [ckeditor/ckeditor4-angular#54]
## Are you reporting a feature request or a bug?
Bug

## Provide detailed reproduction steps (if any)

1. Remove the "undo" plugin from the standard-all preset (default) by using the [config] input
`{
      removePlugins: 'undo'
    };`

### Expected result

Two-way binding works properly

### Actual result

The two-way binding does not work. 
See: https://stackblitz.com/edit/ckeditor4-orm88s

If you comment out the 
`removePlugins: 'undo'`
configuration, the two-way biding works as expected.

## Other details

* Browser: Chrome
* OS: Win10
* Integration version: 1.0.0-beta.2
* CKEditor version: 4.12
* Installed CKEditor plugins: …

**Comment by f1ames** [comment]
I can confirm this issue based on sample provided. That's strange TBH 🤔 We need to investigate it.

Thanks for reporting 👍
