### ISSUE TITLE
Not able to add image upload plugin in angular 7

### ISSUE THREAD

**Issue by kapilsinghal13465** [ckeditor/ckeditor4-angular#57]
## Provide detailed reproduction steps (if any)

1. …
2. …
3. …

### Expected result

*What is the expected result of the above steps?*

### Actual result

*What is the actual result of the above steps?*

## Other details

* Browser: …
* OS: …
* Integration version: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by Dumluregn** [comment]
Hello, I think you forgot to properly fill the issue template. Please do it, because otherwise we are unable to understand your issue well and help.

**Comment by Dumluregn** [comment]
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.
