### ISSUE TITLE
Enable classic editor

### ISSUE THREAD

**Issue by engineering-this** [ckeditor/ckeditor4-angular#6]
CKEditor component is forcing `divarea` plugin. We should should enable use of the classic editor.

Currently we are unable to fix this issue. Usage of framed editor in Angular can cause some memory leaks, and console errors. Angular doesn't allow cleanup before elements are removed from DOM, `ngOnDestroy` is called when elements are already removed.

There is a feature request on Angular GH: https://github.com/angular/angular/issues/17404
Once it is resolved we can allow the usage of classic editor.

**Comment by f1ames** [comment]
This issue will be fixed by upstream issue - https://github.com/ckeditor/ckeditor-dev/pull/3128 and then we can enable classic editor in the integration.

**Comment by engineering-this** [comment]
I wonder if we should keep `divarea` as default editor type, so no breaking changes are introduced? Or change it to `classic`?

If we accept breaking changes during beta phase, we can consider going further, and allow `type=inline` and `type=classic` only. This would allow us to get rid of logic to ensure divarea plugin included in config. In that case if you want to have divarea, just add that plugin to your config.

**Comment by wwalc** [comment]
Since we had a beta release so far, there is no need for keeping backwards compatibility. It should be enough to explain any changes in the changelog and the blog post.
