### ISSUE TITLE
Getting cursor position in ckeditor4-angular 

### ISSUE THREAD

**Issue by Chinna2405** [ckeditor/ckeditor4-angular#63]
## Provide detailed reproduction steps (if any)

1. I tried to get the cursor Position my editor but i couldn't do that?
2. Get error when using getSelection() methos
3. …

### Expected result

*What is the expected result of the above steps?*

### Actual result

*What is the actual result of the above steps?*

## Other details

* Browser: …
* OS: …
* Integration version: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by Dumluregn** [comment]
Hi,
from the information you provided it's hard to understand your problem. Please give us more details and preferably a sample where we could reproduce the issue (for reference see #54).

**Comment by Chinna2405** [comment]
Okay. I will explain below about my issue.

In my issue, I am trying to add some elements from the list outside the editor by clicking it.
But when I typed my whole content in the editor and I chose a place where to insert the element which i am going to click is getting added in the next of whole content but i need to get that element in my cursor position where i have clicked the cursor.

I have tried but couldn't able to get the cursor position.

Please help me to fix the issue.

Thanks in Advance.

**Comment by Dumluregn** [comment]
Thanks for giving more context, I'm starting to understand your issue, but still need something more, like at least screen or [CodePen example](https://codepen.io/). Also I wonder if this is anyhow connected to Angular? Because it seems irrelevant 🤔

**Comment by Chinna2405** [comment]
I have found a way to insert the selected text in the editor.

this.editor.instance.insertText('selected text');

Thanks for spending your valuable time in this issue.
