### ISSUE TITLE
Element Ref is not generic error is thrown in Angular 5 on build

### ISSUE THREAD

**Issue by Chinna2405** [ckeditor/ckeditor4-angular#66]
## Provide detailed reproduction steps (if any)

1.On running the ng build command i am getting the below error.
2.ERROR in node_modules/ckeditor4-angular/ckeditor.component.d.ts(113,29): error TS2315: Type 'ElementRef' is not generic.

### Expected result

*What is the expected result of the above steps?*

### Actual result

*What is the actual result of the above steps?*

## Other details

* Browser: …
* OS: …
* Integration version: …
* Angular version: 5.x.x
* CKEditor version:0.1.0
* Installed CKEditor plugins: …

Thanks in Advance.

**Comment by f1ames** [comment]
Hello @Chinna2405,
this issue was already addressed in #40 PR. The package with the fix will be released next week.

**Comment by paolomainardi** [comment]
I am having the same issue, is there any workaround before the new release ?

**Comment by f1ames** [comment]
The change needed is quite simple - https://github.com/ckeditor/ckeditor4-angular/pull/40/files#diff-756e5674b9c69ad85fad09a2b0c3e852R194 so you may try apply it manually.

The best bet would be building package from the current `master` like:

```
git clone https://github.com/ckeditor/ckeditor4-angular.git
cd ckeditor4-angular
npm run build-package
```
