### ISSUE TITLE
BlockQuote and Marker is not working

### ISSUE THREAD

**Issue by Chinna2405** [ckeditor/ckeditor4-angular#69]
## Provide detailed reproduction steps (if any)

1.BlockQuote and Marker is not working in my angular project 
2. …
3. …

### Expected result

*What is the expected result of the above steps?*

### Actual result

*What is the actual result of the above steps?*

## Other details

* Browser: …
* OS: …
* Integration version: …
Angular version: 5.x.x
* CKEditor version:0.1.0
* Installed CKEditor plugins: …

**Comment by Dumluregn** [comment]
Hello, please fill the issue template correctly so that we could understand your issue.

**Comment by Dumluregn** [comment]
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.
