### ISSUE TITLE
Expose popular events via event emitters

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor4-angular#7]
Some of the events may be used more often, so we may benefit from registering them as Event Emitters. E.g:

* paste
* drop
* fileUploadRequest
* fileUploadResponse

**Comment by ezintz** [comment]
Hello, please note that I have been updating my pull request https://github.com/ckeditor/ckeditor4-angular/pull/21 😀

**Comment by ezintz** [comment]
What does this label mean? How can I support you to get it to `none`?

**Comment by f1ames** [comment]
Hello @ezintz, if you are asking about `workload:medium` it means it requires medium amount of work (in relative terms) from CKEditor 4 team to be done. We have your PR scheduled for this/next iteration so it should be reviewed in 2 - 3 weeks. Thanks again for contributing and involvement into this project!
