### ISSUE TITLE
Target in the Link was not working in Angular 5

### ISSUE THREAD

**Issue by Chinna2405** [ckeditor/ckeditor4-angular#71]
## Are you reporting a feature request or a bug?

i am reporting a bug regarding the link button in the ckeditor4-angular.

## Provide detailed reproduction steps (if any)

1. When we use link button and create a link with target it doesn't seems to be work.
2. It was simply opening in the new tab for all the target category provided in the editor.

### Expected result

The link with appropriate target should work.

## Other details

* Angular version: 5.x.x
* CKEditor version: 0.1.0

**Comment by Dumluregn** [comment]
Hello, could you provide us some sample code of yours or the html produced by editor in this situation? Please remember that the link inside opened editor will not work.

**Comment by Dumluregn** [comment]
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.
