### ISSUE TITLE
Angular 7 Build Production Error

### ISSUE THREAD

**Issue by trivopr** [ckeditor/ckeditor4-angular#77]
## Provide detailed reproduction steps (if any)
I have problem with production Build with CKEDITOR4-ANGULAR

![errr](https://user-images.githubusercontent.com/15151595/69700427-068f4d80-111d-11ea-8965-7ae0526be035.png)

**Comment by f1ames** [comment]
Hello @trivopr,
can you provide your `package.json` (or rather part of it with dependencies used for building) and your node/npm version so we can try to check what's going on?

**Comment by trivopr** [comment]
Hi @f1ames , here is my package.json :)

![code](https://user-images.githubusercontent.com/15151595/69711771-3a29a200-1134-11ea-94f5-113b5edce546.png)

**Comment by Dumluregn** [comment]
Hi, I see you are using both CKEditor4 and CKEditor5:
```
    "@ckeditor/ckeditor5-angular": "^1.1.0",
    "@ckeditor/ckeditor5-build-classic": "^12.4.0",
    "@ungap/url-search-params": "^0.1.2",
    "bootstrap": "3.3.1",
    "ckeditor4-angular": "^1.0.0",
```
I think this may cause trouble as in both packages the component is called the same (`ckeditor`). Do you need both editors? If not, please remove the other one and try to generate your production build again.

**Comment by trivopr** [comment]
Hey @Dumluregn ,
I have already removed version 5. But it still happens. But I have a clue, I get an UNDEFINED value with CKEDITOR in the component when I try to declare it. 

![undefine](https://user-images.githubusercontent.com/15151595/69863871-667a2580-12d0-11ea-9f75-43832563569c.png)

**Comment by trivopr** [comment]
Looking at the issue that happened with the build of production on the original Angular 7 application. I tried with a new project with it.

![code](https://user-images.githubusercontent.com/15151595/69937647-e2ad7c80-150d-11ea-85ea-00316ff7491b.png)

**Comment by Dumluregn** [comment]
Could you type the commend you are using to build your app?

**Comment by trivopr** [comment]
I have already solved it by added `"allowSyntheticDefaultImports": true,`  to tsconfig.json.

**Comment by evoytenkoapps** [comment]
I have already solved it by added "allowSyntheticDefaultImports": true, to tsconfig.json.

**Comment by evoytenkoapps** [comment]
I had same problem. I set "buildOptimizer": false in angular.json for production , and is ok.
thx for ckeditor/ckeditor4-angular#78

**Comment by saket-vanama** [comment]
I am getting same problem while using ckeditor4-angular. Tried "allowSyntheticDefaultImports": true, to tsconfig.json. and "buildOptimizer": false but no luck.
