### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by InventSuriya** [ckeditor/ckeditor4-angular#79]
ERROR in ./node_modules/ckeditor4-angular/fesm5/ckeditor4-angular.js

**Comment by jacekbogdanski** [comment]
We would like to help solve your issue but it seems you have missed our [template for feature requests and bug reports](https://github.com/ckeditor/ckeditor-dev/blob/major/.github/ISSUE_TEMPLATE.md). Its purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.

Please refer to [our guide on how to report issues](https://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates) on the tracker, and open a new issue using the template as this one is being closed now.

**Comment by InventSuriya** [comment]
Thank you so much for help me to solve this issue.

**Comment by carloshoffmann** [comment]
and the solution?

**Comment by f1ames** [comment]
@InventSuriya, did you do something specific which may help @carloshoffmann to solve this issue to?

@carloshoffmann you may also take a look at #77. If none of that helps, please report a new issue with your detailed case.
