### ISSUE TITLE
How to configure the component to use the full preset?

### ISSUE THREAD

**Issue by brucebrit** [ckeditor/ckeditor4-angular#83]
The current ckeditor4-angular component uses the standard preset. Any way to configure to siwtch to the full preset?

**Comment by brucebrit** [comment]
I answer my own question. Use 
<ckeditor editorUrl="https://cdn.ckeditor.com/4.13.1/full/ckeditor.js">

**Comment by f1ames** [comment]
For a future reference, please see [documentation on Customizing CKEditor Preset or Version](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_angular.html#customizing-ckeditor-preset-or-version).
