### ISSUE TITLE
Bump year in licence header (footer actually) on npm

### ISSUE THREAD

**Issue by Dumluregn** [ckeditor/ckeditor4-angular#85]
## Are you reporting a feature request or a bug?

Task

## Provide detailed reproduction steps (if any)

[NPM](https://www.npmjs.com/package/ckeditor4-angular#license)

<img width="687" alt="Screenshot 2020-02-03 at 09 00 51" src="https://user-images.githubusercontent.com/10883184/73635397-bde79980-4663-11ea-8ecf-5a11a3deee49.png">

**Comment by hub33k** [comment]
I think we can close this issue - https://github.com/ckeditor/ckeditor4-angular/commit/85dfe5862c4e1a383158b9ffb4e9f73e912d3613.

**Comment by f1ames** [comment]
Already fixed as mentioned by @hub33k in https://github.com/ckeditor/ckeditor4-angular/issues/85#issuecomment-610867508.
