### ISSUE TITLE
Allow empty html tags

### ISSUE THREAD

**Issue by biswajitpaul01** [ckeditor/ckeditor4-angular#87]
How can I allow i tags for icons. I know that i tags are treated as empty so the editor is removing it. 

In test.component.html file:
~~~html
<ckeditor #myEditor id="editor1" name="editor1" formControlName="pageContent" [config]="config"></ckeditor>
~~~

In test.component.ts file:
~~~javascript
  constructor() {
    this.config = {      
      allowedContent: true,
      removeEmpty: false,
      removeFormatAttributes: '',
      removeFormatTags: ''
    };
  }
~~~

## Provide detailed reproduction steps (if any)

1. When I paste below content in source code:

~~~html
<div class="left-icon-points-icon text-center">
<i class="demo-icon ebi-sketch-line"></i>
</div>
~~~

### Expected result

~~~html
<div class="left-icon-points-icon text-center">
<i class="demo-icon ebi-sketch-line"></i>
</div>
~~~

### Actual result

~~~html
<div class="left-icon-points-icon text-center">
</div>
~~~

* Browser: Google Chrome
* OS: Ubuntu 18.04
* Integration version: ???
* CKEditor version: 4
* Installed CKEditor plugins: n/a

Please help.

**Comment by f1ames** [comment]
Hello @biswajitpaul01,

this is a general CKEditor 4 issue, please refer to this [SO thread](https://stackoverflow.com/questions/18250404/ckeditor-strips-i-tag) for possible solutions.
