### ISSUE TITLE
In Angular component config enterMode and coreStyles_bold doesn't work

### ISSUE THREAD

**Issue by oneclickwebstudio** [ckeditor/ckeditor4-angular#91]
## Type of report
Trying to set
```
const config = {
  ckeditor: {
    enterMode: 2,
    coreStyles_bold : { element: 'b', overrides: 'strong' },
    toolbar: {
      items: ['undo', 'redo', '|', 'bold', 'italic', 'underline', 'strikethrough', 'code', 'link']
    }
  }
};
```
to
`<ckeditor [editor]="Editor" [config]="config" formControlName="about"></ckeditor>
`

### Expected result

While pressing ENTER should create <br/> instead new paragraph
the same with coreStyles_bold

### Actual result

pasting paragraph and strong tag instead of <b>

**Comment by f1ames** [comment]
Closed due to clarification from https://github.com/ckeditor/ckeditor4/issues/3846#issuecomment-584107773.
