### ISSUE TITLE
Upload local image as base64

### ISSUE THREAD

**Issue by dtomaszewski** [ckeditor/ckeditor4-angular#92]
Hi,

How I can add functionality of uploading files from local drive without any server ? I mean to convert this image to base64, display in editor and send it in HTML ?

**Comment by dtomaszewski** [comment]
I found a plugin which seems that it does what I want https://ckeditor.com/cke4/addon/base64image but is there any official way of installing 3rd party plugins with Angular wrapper ?

**Comment by jacekbogdanski** [comment]
Please, refer to [Angular Integration Guide](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_angular.html)

**Comment by dtomaszewski** [comment]
@jacekbogdanski can You point exact place where my question is answered ?
