### ISSUE TITLE
Bump dependencies

### ISSUE THREAD

**Issue by Dumluregn** [ckeditor/ckeditor4-angular#98]
## Are you reporting a feature request or a bug?

Task

## Provide detailed reproduction steps (if any)

[dependencies](https://david-dm.org/ckeditor/ckeditor4-angular)
[devDependencies](https://david-dm.org/ckeditor/ckeditor4-angular?type=dev)

The second one is not as important as the main deps.

**Comment by ezintz** [comment]
Hello, I have been doing this in my fork. Everything is still working, but my changes for additional common events are included so I will wait until that one is merged.

Would it make sense to have different releases for different Angular versions? I was thinking about to go with Angular versions e.g. 9.x.x or 8.x.x for previous version.

**Comment by f1ames** [comment]
Hello @ezintz,

dependencies of `ckeditor4-angular` package are rather minimal - only `load-script` and `tslib` ([see on NPM](https://www.npmjs.com/package/ckeditor4-angular)) so I'm not sure if there is any sense in having different releases for different Angular versions. Do yo think there could be any issue with newer/older Angular versions with those deps?

**Comment by f1ames** [comment]
As for `devDependencies` we have an issue with `@angular-devkit/build-angular` dependency which requires `node-sass@4.10.0` and so we cannot build docs (`ckeditor4-docs`) with never than 10 version of node (because it is used there too).
